package cn.com.sinosoft.usercenter.model;

import java.math.BigDecimal;
import java.util.Date;

public class GeCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CUSTOMERNO
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CUSTOMERACCOUNT
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String customeraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CUSTOMERLEVEL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String customerlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CUSTOMERNAME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.SECURITYPWD
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String securitypwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.PWD
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.EMAIL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.MOBILEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.IDENTIFYTYPE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String identifytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.IDENTIFYNUMBER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String identifynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.SEX
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.BIRTHDAY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.MARRIAGESTATUS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String marriagestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.AREACODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.INDUSTRY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.INCOME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.HOMEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String homephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.OFFICEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String officephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.PROVINCES
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String provinces;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.AREA
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CONTACTADDRESS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String contactaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.ZIPCODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.USERSOURCE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String usersource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.HEALTH
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String health;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.STATUS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.ACTIVECODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String activecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.INTEGRAL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private BigDecimal integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CREATETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.FLAG
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.LOGINTIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private Date logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.LOGINNUM
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private Long loginnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CHECKMAIL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String checkmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CHECKMOBILE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String checkmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CREATEUSER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.UPDATETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.UPDATEUSER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.NATIONALITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.IDVALIDTIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String idvalidtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.IDVALIDTIMESTART
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private Date idvalidtimestart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.IDVALIDTIMEEND
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private Date idvalidtimeend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.CHITIAN
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String chitian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.LOGINMOBILE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String loginmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.REGISTERSTYLE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String registerstyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.UPDATEMOBILETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private Date updatemobiletime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.HASUPDATEACCOUNT
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String hasupdateaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.PWDLEVEL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String pwdlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.USTINFLAG
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String ustinflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.USTINVALUE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String ustinvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.STREET
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_CUSTOMER.COMMUNITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    private String community;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CUSTOMERNO
     *
     * @return the value of GE_CUSTOMER.CUSTOMERNO
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CUSTOMERNO
     *
     * @param customerno the value for GE_CUSTOMER.CUSTOMERNO
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CUSTOMERACCOUNT
     *
     * @return the value of GE_CUSTOMER.CUSTOMERACCOUNT
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCustomeraccount() {
        return customeraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CUSTOMERACCOUNT
     *
     * @param customeraccount the value for GE_CUSTOMER.CUSTOMERACCOUNT
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCustomeraccount(String customeraccount) {
        this.customeraccount = customeraccount == null ? null : customeraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CUSTOMERLEVEL
     *
     * @return the value of GE_CUSTOMER.CUSTOMERLEVEL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCustomerlevel() {
        return customerlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CUSTOMERLEVEL
     *
     * @param customerlevel the value for GE_CUSTOMER.CUSTOMERLEVEL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCustomerlevel(String customerlevel) {
        this.customerlevel = customerlevel == null ? null : customerlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CUSTOMERNAME
     *
     * @return the value of GE_CUSTOMER.CUSTOMERNAME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CUSTOMERNAME
     *
     * @param customername the value for GE_CUSTOMER.CUSTOMERNAME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.SECURITYPWD
     *
     * @return the value of GE_CUSTOMER.SECURITYPWD
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getSecuritypwd() {
        return securitypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.SECURITYPWD
     *
     * @param securitypwd the value for GE_CUSTOMER.SECURITYPWD
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setSecuritypwd(String securitypwd) {
        this.securitypwd = securitypwd == null ? null : securitypwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.PWD
     *
     * @return the value of GE_CUSTOMER.PWD
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.PWD
     *
     * @param pwd the value for GE_CUSTOMER.PWD
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.EMAIL
     *
     * @return the value of GE_CUSTOMER.EMAIL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.EMAIL
     *
     * @param email the value for GE_CUSTOMER.EMAIL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.MOBILEPHONE
     *
     * @return the value of GE_CUSTOMER.MOBILEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.MOBILEPHONE
     *
     * @param mobilephone the value for GE_CUSTOMER.MOBILEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.IDENTIFYTYPE
     *
     * @return the value of GE_CUSTOMER.IDENTIFYTYPE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getIdentifytype() {
        return identifytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.IDENTIFYTYPE
     *
     * @param identifytype the value for GE_CUSTOMER.IDENTIFYTYPE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setIdentifytype(String identifytype) {
        this.identifytype = identifytype == null ? null : identifytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.IDENTIFYNUMBER
     *
     * @return the value of GE_CUSTOMER.IDENTIFYNUMBER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getIdentifynumber() {
        return identifynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.IDENTIFYNUMBER
     *
     * @param identifynumber the value for GE_CUSTOMER.IDENTIFYNUMBER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setIdentifynumber(String identifynumber) {
        this.identifynumber = identifynumber == null ? null : identifynumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.SEX
     *
     * @return the value of GE_CUSTOMER.SEX
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.SEX
     *
     * @param sex the value for GE_CUSTOMER.SEX
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.BIRTHDAY
     *
     * @return the value of GE_CUSTOMER.BIRTHDAY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.BIRTHDAY
     *
     * @param birthday the value for GE_CUSTOMER.BIRTHDAY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.MARRIAGESTATUS
     *
     * @return the value of GE_CUSTOMER.MARRIAGESTATUS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getMarriagestatus() {
        return marriagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.MARRIAGESTATUS
     *
     * @param marriagestatus the value for GE_CUSTOMER.MARRIAGESTATUS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setMarriagestatus(String marriagestatus) {
        this.marriagestatus = marriagestatus == null ? null : marriagestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.AREACODE
     *
     * @return the value of GE_CUSTOMER.AREACODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.AREACODE
     *
     * @param areacode the value for GE_CUSTOMER.AREACODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.INDUSTRY
     *
     * @return the value of GE_CUSTOMER.INDUSTRY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.INDUSTRY
     *
     * @param industry the value for GE_CUSTOMER.INDUSTRY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.INCOME
     *
     * @return the value of GE_CUSTOMER.INCOME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.INCOME
     *
     * @param income the value for GE_CUSTOMER.INCOME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setIncome(String income) {
        this.income = income == null ? null : income.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.HOMEPHONE
     *
     * @return the value of GE_CUSTOMER.HOMEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getHomephone() {
        return homephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.HOMEPHONE
     *
     * @param homephone the value for GE_CUSTOMER.HOMEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setHomephone(String homephone) {
        this.homephone = homephone == null ? null : homephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.OFFICEPHONE
     *
     * @return the value of GE_CUSTOMER.OFFICEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getOfficephone() {
        return officephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.OFFICEPHONE
     *
     * @param officephone the value for GE_CUSTOMER.OFFICEPHONE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setOfficephone(String officephone) {
        this.officephone = officephone == null ? null : officephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.PROVINCES
     *
     * @return the value of GE_CUSTOMER.PROVINCES
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getProvinces() {
        return provinces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.PROVINCES
     *
     * @param provinces the value for GE_CUSTOMER.PROVINCES
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setProvinces(String provinces) {
        this.provinces = provinces == null ? null : provinces.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CITY
     *
     * @return the value of GE_CUSTOMER.CITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CITY
     *
     * @param city the value for GE_CUSTOMER.CITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.AREA
     *
     * @return the value of GE_CUSTOMER.AREA
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.AREA
     *
     * @param area the value for GE_CUSTOMER.AREA
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CONTACTADDRESS
     *
     * @return the value of GE_CUSTOMER.CONTACTADDRESS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getContactaddress() {
        return contactaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CONTACTADDRESS
     *
     * @param contactaddress the value for GE_CUSTOMER.CONTACTADDRESS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setContactaddress(String contactaddress) {
        this.contactaddress = contactaddress == null ? null : contactaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.ZIPCODE
     *
     * @return the value of GE_CUSTOMER.ZIPCODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.ZIPCODE
     *
     * @param zipcode the value for GE_CUSTOMER.ZIPCODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.USERSOURCE
     *
     * @return the value of GE_CUSTOMER.USERSOURCE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getUsersource() {
        return usersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.USERSOURCE
     *
     * @param usersource the value for GE_CUSTOMER.USERSOURCE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setUsersource(String usersource) {
        this.usersource = usersource == null ? null : usersource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.HEALTH
     *
     * @return the value of GE_CUSTOMER.HEALTH
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.HEALTH
     *
     * @param health the value for GE_CUSTOMER.HEALTH
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.STATUS
     *
     * @return the value of GE_CUSTOMER.STATUS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.STATUS
     *
     * @param status the value for GE_CUSTOMER.STATUS
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.ACTIVECODE
     *
     * @return the value of GE_CUSTOMER.ACTIVECODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getActivecode() {
        return activecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.ACTIVECODE
     *
     * @param activecode the value for GE_CUSTOMER.ACTIVECODE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setActivecode(String activecode) {
        this.activecode = activecode == null ? null : activecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.INTEGRAL
     *
     * @return the value of GE_CUSTOMER.INTEGRAL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public BigDecimal getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.INTEGRAL
     *
     * @param integral the value for GE_CUSTOMER.INTEGRAL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setIntegral(BigDecimal integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CREATETIME
     *
     * @return the value of GE_CUSTOMER.CREATETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CREATETIME
     *
     * @param createtime the value for GE_CUSTOMER.CREATETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.FLAG
     *
     * @return the value of GE_CUSTOMER.FLAG
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.FLAG
     *
     * @param flag the value for GE_CUSTOMER.FLAG
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.LOGINTIME
     *
     * @return the value of GE_CUSTOMER.LOGINTIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.LOGINTIME
     *
     * @param logintime the value for GE_CUSTOMER.LOGINTIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.LOGINNUM
     *
     * @return the value of GE_CUSTOMER.LOGINNUM
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public Long getLoginnum() {
        return loginnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.LOGINNUM
     *
     * @param loginnum the value for GE_CUSTOMER.LOGINNUM
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setLoginnum(Long loginnum) {
        this.loginnum = loginnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CHECKMAIL
     *
     * @return the value of GE_CUSTOMER.CHECKMAIL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCheckmail() {
        return checkmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CHECKMAIL
     *
     * @param checkmail the value for GE_CUSTOMER.CHECKMAIL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCheckmail(String checkmail) {
        this.checkmail = checkmail == null ? null : checkmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CHECKMOBILE
     *
     * @return the value of GE_CUSTOMER.CHECKMOBILE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCheckmobile() {
        return checkmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CHECKMOBILE
     *
     * @param checkmobile the value for GE_CUSTOMER.CHECKMOBILE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCheckmobile(String checkmobile) {
        this.checkmobile = checkmobile == null ? null : checkmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CREATEUSER
     *
     * @return the value of GE_CUSTOMER.CREATEUSER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CREATEUSER
     *
     * @param createuser the value for GE_CUSTOMER.CREATEUSER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.UPDATETIME
     *
     * @return the value of GE_CUSTOMER.UPDATETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.UPDATETIME
     *
     * @param updatetime the value for GE_CUSTOMER.UPDATETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.UPDATEUSER
     *
     * @return the value of GE_CUSTOMER.UPDATEUSER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.UPDATEUSER
     *
     * @param updateuser the value for GE_CUSTOMER.UPDATEUSER
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.NATIONALITY
     *
     * @return the value of GE_CUSTOMER.NATIONALITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.NATIONALITY
     *
     * @param nationality the value for GE_CUSTOMER.NATIONALITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.IDVALIDTIME
     *
     * @return the value of GE_CUSTOMER.IDVALIDTIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getIdvalidtime() {
        return idvalidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.IDVALIDTIME
     *
     * @param idvalidtime the value for GE_CUSTOMER.IDVALIDTIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setIdvalidtime(String idvalidtime) {
        this.idvalidtime = idvalidtime == null ? null : idvalidtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.IDVALIDTIMESTART
     *
     * @return the value of GE_CUSTOMER.IDVALIDTIMESTART
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public Date getIdvalidtimestart() {
        return idvalidtimestart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.IDVALIDTIMESTART
     *
     * @param idvalidtimestart the value for GE_CUSTOMER.IDVALIDTIMESTART
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setIdvalidtimestart(Date idvalidtimestart) {
        this.idvalidtimestart = idvalidtimestart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.IDVALIDTIMEEND
     *
     * @return the value of GE_CUSTOMER.IDVALIDTIMEEND
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public Date getIdvalidtimeend() {
        return idvalidtimeend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.IDVALIDTIMEEND
     *
     * @param idvalidtimeend the value for GE_CUSTOMER.IDVALIDTIMEEND
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setIdvalidtimeend(Date idvalidtimeend) {
        this.idvalidtimeend = idvalidtimeend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.CHITIAN
     *
     * @return the value of GE_CUSTOMER.CHITIAN
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getChitian() {
        return chitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.CHITIAN
     *
     * @param chitian the value for GE_CUSTOMER.CHITIAN
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setChitian(String chitian) {
        this.chitian = chitian == null ? null : chitian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.LOGINMOBILE
     *
     * @return the value of GE_CUSTOMER.LOGINMOBILE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getLoginmobile() {
        return loginmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.LOGINMOBILE
     *
     * @param loginmobile the value for GE_CUSTOMER.LOGINMOBILE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setLoginmobile(String loginmobile) {
        this.loginmobile = loginmobile == null ? null : loginmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.REGISTERSTYLE
     *
     * @return the value of GE_CUSTOMER.REGISTERSTYLE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getRegisterstyle() {
        return registerstyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.REGISTERSTYLE
     *
     * @param registerstyle the value for GE_CUSTOMER.REGISTERSTYLE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setRegisterstyle(String registerstyle) {
        this.registerstyle = registerstyle == null ? null : registerstyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.UPDATEMOBILETIME
     *
     * @return the value of GE_CUSTOMER.UPDATEMOBILETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public Date getUpdatemobiletime() {
        return updatemobiletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.UPDATEMOBILETIME
     *
     * @param updatemobiletime the value for GE_CUSTOMER.UPDATEMOBILETIME
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setUpdatemobiletime(Date updatemobiletime) {
        this.updatemobiletime = updatemobiletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.HASUPDATEACCOUNT
     *
     * @return the value of GE_CUSTOMER.HASUPDATEACCOUNT
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getHasupdateaccount() {
        return hasupdateaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.HASUPDATEACCOUNT
     *
     * @param hasupdateaccount the value for GE_CUSTOMER.HASUPDATEACCOUNT
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setHasupdateaccount(String hasupdateaccount) {
        this.hasupdateaccount = hasupdateaccount == null ? null : hasupdateaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.PWDLEVEL
     *
     * @return the value of GE_CUSTOMER.PWDLEVEL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getPwdlevel() {
        return pwdlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.PWDLEVEL
     *
     * @param pwdlevel the value for GE_CUSTOMER.PWDLEVEL
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setPwdlevel(String pwdlevel) {
        this.pwdlevel = pwdlevel == null ? null : pwdlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.USTINFLAG
     *
     * @return the value of GE_CUSTOMER.USTINFLAG
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getUstinflag() {
        return ustinflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.USTINFLAG
     *
     * @param ustinflag the value for GE_CUSTOMER.USTINFLAG
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setUstinflag(String ustinflag) {
        this.ustinflag = ustinflag == null ? null : ustinflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.USTINVALUE
     *
     * @return the value of GE_CUSTOMER.USTINVALUE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getUstinvalue() {
        return ustinvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.USTINVALUE
     *
     * @param ustinvalue the value for GE_CUSTOMER.USTINVALUE
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setUstinvalue(String ustinvalue) {
        this.ustinvalue = ustinvalue == null ? null : ustinvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.STREET
     *
     * @return the value of GE_CUSTOMER.STREET
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.STREET
     *
     * @param street the value for GE_CUSTOMER.STREET
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_CUSTOMER.COMMUNITY
     *
     * @return the value of GE_CUSTOMER.COMMUNITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_CUSTOMER.COMMUNITY
     *
     * @param community the value for GE_CUSTOMER.COMMUNITY
     *
     * @mbggenerated Fri Mar 25 11:31:57 CST 2016
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }
}