package cn.com.sinosoft.usercenter.model;

public class TrlcTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RLC_TEST.TRT_ID
     *
     * @mbggenerated Thu Apr 07 14:49:04 CST 2016
     */
    private String trtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RLC_TEST.TRT_NAME
     *
     * @mbggenerated Thu Apr 07 14:49:04 CST 2016
     */
    private String trtName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RLC_TEST.TRT_ID
     *
     * @return the value of T_RLC_TEST.TRT_ID
     *
     * @mbggenerated Thu Apr 07 14:49:04 CST 2016
     */
    public String getTrtId() {
        return trtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RLC_TEST.TRT_ID
     *
     * @param trtId the value for T_RLC_TEST.TRT_ID
     *
     * @mbggenerated Thu Apr 07 14:49:04 CST 2016
     */
    public void setTrtId(String trtId) {
        this.trtId = trtId == null ? null : trtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RLC_TEST.TRT_NAME
     *
     * @return the value of T_RLC_TEST.TRT_NAME
     *
     * @mbggenerated Thu Apr 07 14:49:04 CST 2016
     */
    public String getTrtName() {
        return trtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RLC_TEST.TRT_NAME
     *
     * @param trtName the value for T_RLC_TEST.TRT_NAME
     *
     * @mbggenerated Thu Apr 07 14:49:04 CST 2016
     */
    public void setTrtName(String trtName) {
        this.trtName = trtName == null ? null : trtName.trim();
    }
}