package cn.com.sinosoft.usercenter.dao;

import java.util.List;

import cn.com.sinosoft.usercenter.model.GeCustomer;

public interface GeCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_CUSTOMER
     *
     * @mbggenerated Thu Mar 24 15:19:47 CST 2016
     */
    int deleteByPrimaryKey(String customerno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_CUSTOMER
     *
     * @mbggenerated Thu Mar 24 15:19:47 CST 2016
     */
    int insert(GeCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_CUSTOMER
     *
     * @mbggenerated Thu Mar 24 15:19:47 CST 2016
     */
    int insertSelective(GeCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_CUSTOMER
     *
     * @mbggenerated Thu Mar 24 15:19:47 CST 2016
     */
    GeCustomer selectByPrimaryKey(String customerno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_CUSTOMER
     *
     * @mbggenerated Thu Mar 24 15:19:47 CST 2016
     */
    int updateByPrimaryKeySelective(GeCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_CUSTOMER
     *
     * @mbggenerated Thu Mar 24 15:19:47 CST 2016
     */
    int updateByPrimaryKey(GeCustomer record);
    
    /**
     * 根据姓名查询
     * @author renlc
     * @param record
     * @return
     */
    List<GeCustomer> selectByCustomerName(String customername);
    /**
     * 根据条件
     * @author renlc
     * @param record
     * @return
     */
    List<GeCustomer> selectBySelective(GeCustomer record);
}