package cn.com.sinosoft.usercenter.dao;

import cn.com.sinosoft.usercenter.model.TrlcTest;

public interface TrlcTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RLC_TEST
     *
     * @mbggenerated Thu Apr 07 14:49:04 CST 2016
     */
    int insert(TrlcTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RLC_TEST
     *
     * @mbggenerated Thu Apr 07 14:49:04 CST 2016
     */
    int insertSelective(TrlcTest record);
}